config/routes.rb
Calendar::Application.routes.draw do 
  
  resources :events

  get "qwerty/index"

  resources :user_sessions

  resources :users
  match 'destroy', :to => 'events#destroy'
  match 'all_events', :to => 'events#all_events'
  match 'calendar', :to => 'qwerty#my_events'

	match 'logout', :to => 'user_sessions#destroy' #, :as => "logout"
	match 'login', :to => 'user_sessions#new'      #, :as => "login"
	

 
	root :to => 'qwerty#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :name, :text, :date
  belongs_to :user
  belongs_to :repeat
  
  validates :name, :presence => true, :length => { :maximum => 140 }
  validates :text, :presence => true
  validates :user_id, :presence => true
  #validates :repeat_id, :presence => true
  
  default_scope :order => 'events.created_at ASC'

end

app/models/repeat.rb
class Repeat < ActiveRecord::Base
  has_many :events
  def name_repeat
   return "#{text}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	acts_as_authentic
	attr_accessible :name, :email, :password, :password_confirmation
  has_many :events, :dependent => :destroy

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery
    
  #filter_parameter_logging :password, :password_confirmation
  helper_method :current_user_session, :current_user

  private
    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = current_user.events.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end
  
  # GET /events
  # GET /events.json
  def all_events
    @events = Event.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end
  # GET /events/1
  # GET /events/1.json
  def show
    @event = current_user.events.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    #@user_id = current_user.id
    @repeats = Repeat.all   #.collect { |repeat| [repeat.id, repeat.text]}
    @event = Event.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event}
    end
  end

  # GET /events/1/edit
  def edit
    @user = current_user 
    @repeats = Repeat.all 
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @repeats = Repeat.all 
    @event = current_user.events.build(params[:event])
 
    respond_to do |format|
      if @event.save
        format.html { redirect_to current_user, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find
    @event.destroy

    respond_to do |format|
      format.html { redirect_to calendar_url }
      format.json { head :ok }
    end
  end
end

app/controllers/qwerty_controller.rb
class QwertyController < ApplicationController
  def index
    
  end
  def my_events
    @user = current_user
    months = {1=>"January",2 => "February", 3 => "March",4 => "April",
      5 => "May",6 => "June", 7 => "July",8 => "August",
      9 => "September",10 => "October", 11 => "November",12 => "December"}
    @month_now = Time.now.month
    
    #текущий месяц
    @month = months[@month_now]
   
    #первое число текущего месяца
    first = Date.today.beginning_of_month
    
    #последнее число месяца
    last = Date.today.end_of_month
    #с какого числа начинается неделя, в течении которой начинается месяц
    @week = first.at_beginning_of_week
   
    # не удается создать выборку за текущий месяц
    puts "first data #{first}"
    puts "last data #{last}"
    @events = current_user.events.find_all_by_date(first..last)
      
  end
  
  
  
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController


  # GET /user_sessions/new
  # GET /user_sessions/new.json
  def new
    @user_session = UserSession.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_session }
    end
  end



  # POST /user_sessions
  # POST /user_sessions.json
  def create
    @user_session = UserSession.new(params[:user_session])

    respond_to do |format|
      if @user_session.save
        format.html { redirect_to calendar_path, notice: 'register was successfully' }
        format.json { render json: @user_session, status: :created, location: @user_session }
      else
        format.html { render action: "new" }
        format.json { render json: @user_session.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /user_sessions/1
  # DELETE /user_sessions/1.json
  def destroy
    @user_session = UserSession.find
    @user_session.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    #    @users = User.all
    @users = User.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = current_user#User.find(params[:id])
    @events = current_user.events.paginate(:page => params[:page])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = current_user #User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, notice: 'registration successfully.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = current_user # User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to root_url, notice: 'User was successfully updated profile' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = current_user
    @user.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/qwerty_helper.rb
module QwertyHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<TABLE>
  <tr>  

    <TD> <%=event.name%></TD>
    <TD><%=event.text%></TD>
    <TD><%=event.date%></TD>
     <TD><%= link_to 'Edit', edit_event_path(event)%></TD>
    <TD><%= link_to 'Destroy', :controller=>"events" , :action=>"destroy", :id=>event %></TD>
  </tr>
</TBODY>
</TABLE>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>


  <%#=  options_from_collection_for_select(@repeats, :id, :name) %>
  <%#= f.collection_select @event, :repeat_id, @repeats, :id, :name_repeat, {:prompt => true} %>




  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/all_events.html.erb
<%= link_to 'home page', root_path %>
<%=link_to "show my events", user_path(:current) %>

<h1>Listing events</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th>Date</th>
    <th>user</th>
    <th>Id repeat</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @events.each do |event| %>
    <tr>
      <td><%= event.name %></td>
      <td><%= event.text %></td>
      <td><%= event.date %></td>


      <td><%if event.user_id == current_user.id%>
          <%= "#{current_user.name}"%></td>
      <%else%>
        <%="anonimus"%>
      <%end%>



      <td><%= event.repeat_id %></td>
  
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>
<%= link_to 'show calendar', calendar_path %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'to calendar', calendar_path %>
<%= link_to 'Destroy',  @event, method: :destroy %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th>Date</th>
    <th>user</th>
    <th>Id repeat</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.text %></td>
    <td><%= event.date %></td>
    <td><%= current_user.name %></td>
    <td><%= event.repeat_id %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', :controller=>"events" , :action=>"destroy", :id=>event %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>
<%= link_to 'show calendar', calendar_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', calendar_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Content:</b>
  <%= @event.text %>
</p>

<p>
  <b>Date:</b>
  <%= @event.date %>
</p>

<p>
  <b>user name:</b>
  <%= current_user.name  %>
</p>

<p>
  <b>Id repeat:</b>
  <%= @event.repeat_id %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', calendar_path %>
<%= link_to 'Destroy', controller: :events , method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calendar</title>

  <%= csrf_meta_tags %>
</head>
<body>

<!--
<div id ="user_nav">
	<%if current_user%>
	<%= link_to 'edit profile', edit_user_path(:current)%> ||
	<%= link_to 'logout', logout_path%>
	<%else%>
	<%= link_to 'register', new_user_path%> ||
	<%= link_to 'login', login_path%>
	<%end%>
</div>
-->


<%= yield %>

</body>
</html>

app/views/qwerty/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby on Rails: Welcome aboard</title>

    <%= stylesheet_link_tag    "qwerty" %>

  </head>

  <body>


    <div id ="user_nav">
      <%if current_user%>
        <%=if current_user.name.empty?
          "hello user #{current_user.email}"
        else
          "hello #{current_user.name}"
        end%>
        <br>        <br>  
        <%= link_to 'edit profile', edit_user_path(:current)%>
        <%= link_to 'all users', users_path%>
        <%= link_to 'log out', logout_path, :class => 'asd'%>
        <%=link_to "go my events", user_path(:current) %>
        <%=link_to "go my calendar", calendar_path(:current) %>

      <%else%>
        <%= link_to 'register', new_user_path%>
        <%= link_to 'log in', login_path, :class => 'asdf'%>
      <%end%>
    </div>

  </body>
</html>

app/views/qwerty/my_events.html.erb
<%= link_to 'Edit my profile', edit_user_path(:current) %> |
<%= link_to 'show all users', users_path %>
<%= link_to 'home page', root_path %>
<%=link_to "show my events", user_path(:current) %>
<%=link_to "add event", new_event_path %>
<%=link_to "show all events", all_events_path %>
<p>

  <%if current_user.name.empty?%>
    <b><%="hello user"%></b>
  <%else%>
    <b><%="your Name"%></b>
    <%= "#{current_user.name}"%>
  <%end%>

</p>

<p>
  <b>your Email:</b>
  <%= current_user.email %>
</p>

<font size="15" color="#000000" align="rigth"> <%="#{@month}"%> </font> 

<font  color="#000000" align="right"> <%=link_to "next_month", calendar_path %></font> 


<%#=@events%>

<TABLE width="100%" border=1 bordercolordark="#000000" bordercolorlight="#FFFFFF" cellpadding="5">
  <TBODY>
    <TR>
      <TH valign=center align=middle width="14%" bgcolor="#000000"><font size="1" color="#FFFFFF" face="Verdana">
        Monday</font></TH>
      <TH valign=center align=middle width="14%" bgcolor="#000000"><font size="1" color="#FFFFFF" face="Verdana">
        Tuesday</font>    </TH>
      <TH valign=center align=middle width="14%" bgcolor="#000000"><font size="1" color="#FFFFFF" face="Verdana">
        Wednesday</font>    </TH>
      <TH valign=center align=middle width="14%" bgcolor="#000000"><font size="1" color="#FFFFFF" face="Verdana">
        Thursday</font>    </TH>
      <TH valign=center align=middle width="14%" bgcolor="#000000"><font size="1" color="#FFFFFF" face="Verdana">
        Friday</font></TH>
      <TH valign=center align=middle width="14%" bgcolor="#000000"><font size="1" color="#FFFFFF" face="Verdana">
        Saturday</font></TH>
      <TH valign=center align=middle width="14%" bgcolor="#000000"><font size="1" color="#FFFFFF" face="Verdana">
        Sunday</font></TH>
    </TR>
    <%for m in 1..6 %><TR>

        <%for n in 1..7 %>
          <%data = @week.day%>
          <%if @month_now == @week.month%>
            <TD vAlign=top align=left width="14%" bgcolor="#afcddf" >
            <%else%>
            <TD vAlign=top align=left width="14%"> 
            <%end%>
            <%="#{data}"%>

            <%
            @events.each do |event|
              if event.date.nil? == false
                qwerty=Date.parse("#{event.date}")
                if qwerty.month == @week.month
                  if qwerty.day == @week.day%>
                    <%= link_to "#{event.name}", edit_event_path(event) %>
                  <%
                  end
                else
                  "net daty"
                end
              end
            end
          %>
            <br><br><br><br></TD>


          <%if([4,6,9,11].include?(@week.month))
            if ((@week.day).to_i)<30
              @week = Date.new(@week.year,@week.month,(@week.day).to_i + 1)
            else
              @week = Date.new(@week.year,(@week.month).to_i+1,1)
            end

          else
            if @week.month == 2
              if ((@week.day).to_i)<31
                @week = Date.new(@week.year,@week.month,(@week.day).to_i + 1)
              else
                @week = Date.new(@week.year,(@week.month).to_i+1,1)
              end
            else
              if ((@week.day).to_i)<31
                @week = Date.new(@week.year,@week.month,(@week.day).to_i + 1)
              else
                @week = Date.new(@week.year,(@week.month).to_i+1,1)
              end
            end
          end%>
        <%end%>
      </TR>
    <%end%>
  </TBODY>
</TABLE>

app/views/user_sessions/_form.html.erb
<%= form_for(@user_session) do |f| %>
  <% if @user_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_session.errors.count, "error") %> registration is not successful</h2>

      <ul>
      <% @user_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
  <br>
    <%= f.submit  'Login'%>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>log in</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>



<%= render 'form' %> 
<%= link_to 'Back', root_path %>
<%= link_to 'Destroy', controller: :users , method: :delete %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table border="1" >
  <tr>
    <th>Name</th>
    <th>Email</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
    </tr>
  <% end %>
</table>

<br />
<%= will_paginate %>
<%= link_to 'home page', root_path %>
<%= link_to 'calendar', calendar_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<%= link_to 'Edit my profile', edit_user_path(@user) %> |
<%= link_to 'show all users', users_path %>
<%= link_to 'home page', root_path %>
<%=link_to "go my calendar", calendar_path(:current) %>
<p>
  <b>your Name:</b>
  <%= @user.name -%>
</p>

<p>
  <b>your Email:</b>
  <%= @user.email -%>
</p>



<% unless @user.events.empty? %>
  <table class="events" summary="User events">
    <%= render @events %>
  </table>  
<% end %>

<%#= will_paginate @events %>
<%=link_to 'new event', new_event_path%>